name: Run tests

on:
  workflow_call:
    secrets:
      secrets:
      NPM_AUTH_TOKEN:
        required: true
        description: 'NPM token with access to repository'
    inputs:
      BRANDEMBASSY_SCOPE_REGISTRY_URL:
        required: false
        type: string
        description: 'Registry URL for brandembassy scoped packages'
        default: 'https://registry.npmjs.org/'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: 'yarn'
          registry-url: 'https://registry.npmjs.org'
      - name: Setup .npmrc
        run: |
          npm config set @brandembassy:registry=$BRANDEMBASSY_SCOPE_REGISTRY_URL
          npm config set $BRANDEMBASSY_SCOPE_REGISTRY_URL:_authToken=$NPM_AUTH_TOKEN
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
          BRANDEMBASSY_SCOPE_REGISTRY_URL: ${{ inputs.BRANDEMBASSY_SCOPE_REGISTRY_URL }}
      - run: npm rebuild
      - run: yarn build
