name: Run eslint

on:
  workflow_call:
    secrets:
      NPM_AUTH_TOKEN:
        required: true
        description: 'NPM token with access to repository'
      NPM_GITHUB_PACKAGES_TOKEN:
        required: true
        description: 'NPM token with access to GitHub packages registry'
    inputs:
      maxWarnings:
        default: 0
        description: 'Max allowed warnings count [default: 0] (-1 for disable)'
        required: false
        type: number

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: 'npm'
      - name: Setup .npmrc
        run: |
          npm config set @BrandEmbassy:registry=https://npm.pkg.github.com
          npm config set //npm.pkg.github.com/:_authToken=$NPM_GITHUB_PACKAGES_TOKEN
          npm config set registry=https://registry.npmjs.org/
          npm config set //registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
          NPM_GITHUB_PACKAGES_TOKEN: ${{ secrets.NPM_GITHUB_PACKAGES_TOKEN }}
      - run: npm install --ignore-scripts
      - run: npm rebuild
      - run: npm run lint -- --max-warnings ${{ inputs.maxWarnings }}
