name: Run eslint

on:
  workflow_call:
    secrets:
      NPM_AUTH_TOKEN:
        required: true
        description: 'NPM token with access to repository'

    inputs:
      maxWarnings:
        default: 0
        description: 'Max allowed warnings count [default: 0] (-1 for disable)'
        required: false
        type: number

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - uses: actions/checkout@v3
      - uses: BrandEmbassy/github-actions/.github/workflows/js-node-setup.yml@master
      - uses: BrandEmbassy/github-actions/.github/workflows/js-yarn-install.yml@master
      - run: yarn lint --max-warnings ${{ inputs.maxWarnings }}
