name: Run node setup

on:
  workflow_call:

jobs:
  setup:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: 'npm'
