name: Run node setup

on:
  workflow_call:
    inputs:
      REGISTRY_URL:
        required: false
        description: 'NPM registry URL'
        default: 'https://registry.npmjs.org'
        type: string

jobs:
  setup:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: 'yarn'
          registry-url: ${{ inputs.REGISTRY_URL }}
