name: Publish to Github Packages

on:
  workflow_call:
    secrets:
      NPM_AUTH_TOKEN:
        required: true
        description: 'NPM token with read access to @brandembassy repositories'

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: BrandEmbassy/github-actions/.github/workflows/js-node-setup.yml@master
      - uses: BrandEmbassy/github-actions/.github/workflows/js-yarn-install.yml@master

      - run: yarn build

      # Publish to Github Packages
      - uses: actions/setup-node@v3
        with:
          registry-url: 'https://npm.pkg.github.com'
      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
