name: Run tests

on:
  workflow_call:
    secrets:
      NPM_GITHUB_PACKAGES_TOKEN:
        required: true
        description: 'NPM token with access to repository'


jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: 'yarn'
      - run: |
          npm config set //npm.pkg.github.com._authToken $NPM_GITHUB_PACKAGES_TOKEN
          yarn config list
          yarn install --frozen-lockfile --ignore-scripts
        env:
          NPM_GITHUB_PACKAGES_TOKEN: ${{ secrets.NPM_GITHUB_PACKAGES_TOKEN }}
        # Skip post-install scripts here, as a malicious script could steal NODE_AUTH_TOKEN.
      - run: yarn rebuild
      - run: yarn test
