
name: Create a new version

on:
  workflow_call:
    secrets:
      NPM_AUTH_TOKEN:
        required: true
        description: 'GH token with access to repository'
    inputs:
      VERSION_TYPE:
        description: 'Type of version to create (minor, major, patch)'
        required: false
        default: 'minor'
        type: string
      VERSION_PREFIX:
        description: 'Should the version have a prefix like v1.1.1'
        required: false
        default: true
        type: boolean


jobs:
  version:
    runs-on: ubuntu-latest
    if: "github.event.head_commit.author.email != 'github-actions@github.com'"
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.NPM_AUTH_TOKEN }}
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: Create a new version
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          yarn version --${{ inputs.VERSION_TYPE }}
          NEW_VERSION_TAG=`git describe --abbrev=0 --tags`
          # Check if VERSION_PREFIX is set to false and remove 'v' prefix accordingly
          if [ "${{ inputs.VERSION_PREFIX }}" = "false" ]; then
            NEW_VERSION_TAG="${NEW_VERSION_TAG:1}"
          fi
          git push --atomic origin master $NEW_VERSION_TAG --force-with-lease
