name: Yarn install

on:
  workflow_call:
    inputs:
      REGISTRY_URL:
        required: false
        description: 'NPM registry URL'
        default: 'https://registry.npmjs.org'
        type: string
    secrets:
      NPM_AUTH_TOKEN:
        required: true
        description: 'NPM token with access to repository'

jobs:
  install:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: 'yarn'
          registry-url: ${{ inputs.REGISTRY_URL }}
      # Skip post-install scripts here, as a malicious script could steal NODE_AUTH_TOKEN.
      - run: yarn install --frozen-lockfile --ignore-scripts
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      - run: npm rebuild
