name: PHP Unit

on:
  workflow_call:
    secrets:
      COMPOSER_TOKEN:
        required: true
        description: 'composer token'
    inputs:
      COMPOSER_ARG:
         required: false
         type: string
         description: 'PHP version'
         default: 'install'
      PHP_VERSION:
        required: false
        type: string
        description: 'PHP version'
        default: '8.1'
      PHP_EXTENSIONS:
        required: false
        type: string
        description: 'A list of PHP extensions to install'
        default: 'mbstring,sockets'
      PHP_INI_VALUES:
        required: false
        type: string
        description: 'PHP ini values'
        default: ''
      RUNS_ON:
        required: false
        type: string
        description: 'Runs on'
        default: 'ubuntu-latest'

jobs:
  phpstan:
    name: PHPStan
    runs-on: ${{ inputs.RUNS_ON }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          ini-values: ${{ inputs.PHP_INI_VALUES }}
          php-version: ${{ inputs.PHP_VERSION }}
          extensions:  ${{ inputs.PHP_EXTENSIONS }}

      - name: Cache composer dependencies
        uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: |
          composer config github-oauth.github.com ${{ secrets.COMPOSER_TOKEN }}
          composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Copy phpstan.neon.example to phpstan.neon if it exists
        run: |
          if [ -f phpstan.neon.example ]; then
            cp phpstan.neon.example phpstan.neon
          else
            echo "phpstan.neon.example does not exist, skipping copy."
          fi

      - name: Cache phpstan
        uses: actions/cache@v4
        with:
          path: ./temp/phpstan
          key: ${{ runner.os }}-phpstan-${{ hashFiles('**/composer.lock') }}-${{ github.ref }}
          restore-keys: |
            ${{ runner.os }}-phpstan-${{ hashFiles('**/composer.lock') }}-
            ${{ runner.os }}-phpstan-

      - name: PHPStan
        run: composer phpstan
