name: Check PR format and title
on:
  workflow_call:

jobs:
  jira-reference:
    name: "Check title contains Jira reference"
    runs-on: ubuntu-latest

    steps:
      - name: Check
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: |
          if [[ "$PR_TITLE" =~ (DE|BECS|CON)-[0-9]+[[:space:]:].{5,} ]]; then
            echo "It's there!"
            exit 0
          else
            echo "Title is missing JIRA ticket! PR title should contains DE-XXX, BECS-XXX or CON-XXX followed by a short description."
            exit 1
          fi
  description:
    name: Check body contains description and possible impact
    runs-on: ubuntu-latest
    # We don't want to run this check on dependabot PR's
    # https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions#responding-to-events
    if: github.actor != 'dependabot[bot]' && github.actor != 'dependabot-preview[bot]'
    steps:
      - name: Check if PR was created by Dependabot
        id: check_dependabot
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_AUTHOR=$(gh pr view ${{ github.event.pull_request.number }} --repo ${{ github.repository }} --json author --jq '.author.login')
          echo "PR Author: $PR_AUTHOR"
          if [[ "$PR_AUTHOR" == "app/dependabot" ]]; then
            echo "Running for Dependabot PR"
            echo "PR_WAS_CREATED_BY_DEPENDABOT=1" >> "$GITHUB_OUTPUT"
          else
            echo "Not a Dependabot PR"
            echo "PR_WAS_CREATED_BY_DEPENDABOT=0" >> "$GITHUB_OUTPUT"
          fi

      - name: Check
        if: steps.check_dependabot.outputs.PR_WAS_CREATED_BY_DEPENDABOT == '0'
        env:
          PR_BODY: ${{ github.event.pull_request.body }}
        run: |
          if [[ "$PR_BODY" =~ .*([Pp]ossible[[:space:]][Ii]mpact:.{3,}[Dd]escription:.{4,}|[Dd]escription:.{4,}[Pp]ossible[[:space:]][Ii]mpact:.{3,}) ]]; then
            echo "It's there!"
            exit 0
          else
            echo "Possible impact or description is missing!"
            exit 1
          fi
