name: Check PR format and title
on:
  workflow_call:

jobs:
  jira-reference:
    name: "Check title contains Jira reference"
    runs-on: ubuntu-latest

    steps:
      - name: Check
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: |
          if [[ $PR_TITLE =~ (DE|BECS)-[0-9]+[[:space:]].{5,} ]]; then
            echo "It's there!"
            exit 0
          else
            echo "Title is missing JIRA ticket! PR title should contains DE-XXX or BECS-XXX followed by a short description."
            exit 1
          fi
  description:
    name: Check body contains description and possible impact
    runs-on: ubuntu-latest
    steps:
      - name: Check
        env:
          PR_BODY: ${{ github.event.pull_request.body }}
        run: |
          if [[ $PR_BODY =~ .*([Pp]ossible[[:space:]][Ii]mpact:.{3,}[Dd]escription:.{4,}|[Dd]escription:.{4,}[Pp]ossible[[:space:]][Ii]mpact:.{3,}) ]]; then
            echo "It's there!"
            exit 0
          else
            echo "Possible impact or description is missing!"
            exit 1
          fi
