name: Pull Request Stats
on:
  workflow_call:
    inputs:
      period:
        description: 'Period in days'
        type: string
        default: '30'
      sortBy:
        description: 'Sort by'
        type: string
        default: 'COMMENTS'
      teamsWebhookUrl:
        description: 'Webhook'
        required: true
        type: string

jobs:
  stats:
    runs-on: ubuntu-latest
    steps:
      - name: Send pull request stats
        uses: flowwer-dev/pull-request-stats@master
        with:
          repositories: ${{ github.repository }}
          token: ${{ secrets.GITHUB_TOKEN }}
          period: ${{ inputs.period }}
          sortBy: ${{ inputs.sortBy }}
          webhook: 'https://channels-eu1-qa.brandembassy.com/jenkins-dashboard/api/github/pull-request-stats?teamsWebhook=${{ inputs.teamsWebhookUrl }}'
