name: Bump version

on:
  workflow_call:

jobs:
  tag-master:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          INITIAL_VERSION: ${{ secrets.TAG_VERSION_PREFIX }}
          DEFAULT_BUMP: patch # patch is used because we are using XX.Y as version prefix
